name: Docker Image CI

on:
  push:
    branches: [ "main","citest"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: mkdir test && ls
